name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04-arm
    container:
      image: swift:6.3-noble
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        run: swift test
